// Machine types
export interface Machine {
  id: string;
  name: string;
  status: 'online' | 'offline';
  lastSeen: Date | null;
  config: MachineConfig | null;
  createdAt: Date;
}

export interface MachineConfig {
  projects: string[];
  agentUrl?: string; // e.g., "localhost:4678" or "mac.tailnet.ts.net:4678"
}

// Session types
export interface Session {
  id: string;
  machineId: string;
  project: string | null;
  status: SessionStatus;
  tmuxSession: string | null;
  startedAt: Date;
  endedAt: Date | null;
}

// Ralph Loop configuration (original implementation)
export interface RalphLoopConfig {
  prompt: string;
  maxIterations?: number;
  completionPromise?: string;
  useWorktree?: boolean; // Create isolated git worktree for this loop
  trustMode?: boolean; // Auto-accept all Claude tool permissions (--dangerously-skip-permissions)
}

// Ralph Loop Prompt Builder types
export type RalphDeliverable = 'tests' | 'readme' | 'types' | 'docs' | 'custom';

export interface RalphPromptBuilder {
  taskDescription: string;
  successCriteria: string[];
  deliverables: RalphDeliverable[];
  customDeliverable?: string;
}

// Labels for deliverables
export const RALPH_DELIVERABLE_LABELS: Record<RalphDeliverable, string> = {
  tests: 'Unit/integration tests with >80% coverage',
  readme: 'Updated README documentation',
  types: 'TypeScript types and interfaces',
  docs: 'Code comments and JSDoc',
  custom: '', // Uses customDeliverable value
};

// Suggested success criteria for quick selection
export const RALPH_SUCCESS_CRITERIA_SUGGESTIONS = [
  'All tests pass',
  'No TypeScript errors',
  'No linter errors',
  'Code coverage >80%',
  'Build succeeds',
] as const;

// User types
export interface User {
  id: string;
  email: string;
  name: string | null;
  createdAt: Date;
}

// WebSocket message types - Client to Agent (Terminal)
export type WSMessageToAgent =
  | { type: 'input'; data: string }
  | { type: 'resize'; cols: number; rows: number }
  | { type: 'start-claude' }
  | { type: 'start-claude-ralph'; config: RalphLoopConfig }
  | { type: 'ping' }
  | { type: 'request-history'; lines?: number };

// WebSocket message types - Agent to Client (Terminal)
export type WSMessageFromAgent =
  | { type: 'output'; data: string }
  | { type: 'connected'; session: string }
  | { type: 'disconnected' }
  | { type: 'pong' }
  | { type: 'history'; data: string; lines: number };

// Session status types for real-time updates
// 4 states: init (starting), working (active), needs_attention (user intervention needed), idle (session ended)
export type SessionStatus = 'init' | 'working' | 'needs_attention' | 'idle';

// Reason why Claude needs attention
export type AttentionReason =
  | 'permission' // Claude needs permission to use a tool
  | 'input' // Claude is waiting for user input
  | 'plan_approval' // Claude has a plan to approve (ExitPlanMode)
  | 'task_complete'; // Claude finished the task

// ============================================================================
// Project Types (v7)
// ============================================================================

export type ProjectStatus = 'planning' | 'active' | 'completed' | 'archived';

export interface Project {
  id: string;
  name: string;
  description: string | null;
  status: ProjectStatus;
  trustMode: boolean;
  worktreePath: string | null;
  branchName: string | null;
  plan: string | null; // Markdown generated by Claude
  baseProject: string | null; // Reference to projects whitelist
  createdAt: number;
  updatedAt: number;
  archivedAt: number | null;
  // Computed fields
  issueCount?: number;
  issuesDone?: number;
}

// ============================================================================
// Issue Types (v7)
// ============================================================================

export type IssueStatus = 'backlog' | 'todo' | 'in_progress' | 'done';
export type IssuePriority = 0 | 1 | 2 | 3 | 4; // 0=none, 1=low, 2=medium, 3=high, 4=urgent

export const ISSUE_PRIORITY_LABELS: Record<IssuePriority, string> = {
  0: 'No priority',
  1: 'Low',
  2: 'Medium',
  3: 'High',
  4: 'Urgent',
};

export const ISSUE_STATUS_LABELS: Record<IssueStatus, string> = {
  backlog: 'Backlog',
  todo: 'Todo',
  in_progress: 'In Progress',
  done: 'Done',
};

export interface Issue {
  id: string;
  projectId: string | null;
  title: string;
  description: string | null;
  status: IssueStatus;
  priority: IssuePriority;
  sessionName: string | null; // Link to active session when running
  plan: string | null; // Detailed execution plan
  orderIndex: number;
  createdAt: number;
  updatedAt: number;
  completedAt: number | null;
  // Computed fields
  project?: Project;
}

export type StatusSource = 'hook' | 'tmux';

// Session info for status WebSocket
export interface WSSessionInfo {
  name: string;
  project: string;
  status: SessionStatus;
  attentionReason?: AttentionReason; // Why Claude needs attention (only set when status is 'needs_attention')
  statusSource: StatusSource;
  lastEvent?: string;
  lastStatusChange?: number;
  createdAt: number;
  lastActivity?: number;
  archivedAt?: number; // Timestamp when session was archived (undefined = active)
  environmentId?: string; // Track which environment this session uses
  // Environment metadata for UI display
  environment?: {
    id: string;
    name: string;
    provider: EnvironmentProvider;
    icon: EnvironmentIcon | null;
    isDefault: boolean;
  };
  // StatusLine metrics (from Claude Code heartbeat)
  model?: string; // Current model display name
  costUsd?: number; // Total cost in USD
  contextUsage?: number; // Context window usage percentage (0-100)
  linesAdded?: number; // Total lines of code added
  linesRemoved?: number; // Total lines of code removed
  // Git worktree isolation
  worktreePath?: string; // Path to worktree if session uses isolation
  branchName?: string; // Branch name for worktree session
}

// WebSocket message types - Client to Agent (Status channel)
export type WSStatusMessageToAgent = { type: 'status-subscribe' } | { type: 'status-unsubscribe' };

// WebSocket message types - Agent to Client (Status channel)
export type WSStatusMessageFromAgent =
  | { type: 'sessions-list'; sessions: WSSessionInfo[] }
  | { type: 'status-update'; session: WSSessionInfo }
  | { type: 'session-removed'; sessionName: string }
  | { type: 'session-archived'; sessionName: string; session: WSSessionInfo }
  | { type: 'version-info'; agentVersion: string }
  | { type: 'update-pending'; targetVersion: string; message: string }
  // Project updates (v7)
  | { type: 'projects-list'; projects: Project[] }
  | { type: 'project-update'; project: Project }
  | { type: 'project-removed'; projectId: string }
  // Issue updates (v7)
  | { type: 'issues-list'; issues: Issue[] }
  | { type: 'issue-update'; issue: Issue }
  | { type: 'issue-removed'; issueId: string }
  // Planning session messages (v7)
  | { type: 'planning-question'; projectId: string; question: PlanningQuestion }
  | { type: 'planning-progress'; projectId: string; phase: PlanningPhase; message: string }
  | { type: 'plan-ready'; projectId: string; plan: string; issues: IssueSpec[] }
  | { type: 'planning-error'; projectId: string; error: string };

// WebSocket message types - Client to Agent (Planning channel)
export type WSPlanningMessageToAgent =
  | { type: 'start-planning'; projectId: string; trustMode?: boolean }
  | { type: 'answer-question'; projectId: string; questionId: string; answer: string }
  | { type: 'approve-plan'; projectId: string }
  | { type: 'reject-plan'; projectId: string; feedback?: string }
  | { type: 'cancel-planning'; projectId: string }
  | { type: 'planning-input'; projectId: string; input: string };

// WebSocket message types - Agent to Client (Planning channel)
export type WSPlanningMessageFromAgent =
  | { type: 'planning-question'; projectId: string; question: PlanningQuestion }
  | { type: 'planning-progress'; projectId: string; phase: PlanningPhase; message: string }
  | { type: 'plan-ready'; projectId: string; plan: string; issues: IssueSpec[] }
  | { type: 'planning-error'; projectId: string; error: string }
  | { type: 'planning-output'; projectId: string; output: string }
  | { type: 'issues-created'; projectId: string; issueIds: string[] };

// Planning types (v7)
export type PlanningPhase = 'gathering' | 'planning' | 'review' | 'complete' | 'error';

export interface PlanningQuestion {
  id: string;
  question: string;
  type: 'text' | 'choice' | 'confirm';
  options?: string[];
  required: boolean;
}

export interface IssueSpec {
  title: string;
  description: string;
  priority: IssuePriority;
  plan?: string; // Detailed execution plan for the issue
  dependencies?: string[]; // Titles of other issues this depends on
}

// API types
export interface RegisterMachineRequest {
  id: string;
  name: string;
  config?: MachineConfig;
}

export interface AgentInfo {
  machine: {
    id: string;
    name: string;
  };
  status: 'online' | 'offline';
  projects: string[];
}

// Editor types
export interface EditorConfig {
  enabled: boolean;
  portRange: { start: number; end: number };
  idleTimeout: number; // ms - shutdown after inactivity
}

export interface EditorStatus {
  project: string;
  running: boolean;
  port?: number;
  pid?: number;
  startedAt?: number;
  lastActivity?: number;
}

// Environment types
export type EnvironmentProvider = 'anthropic' | 'openrouter';

// Available icons for environments
export const ENVIRONMENT_ICON_OPTIONS = [
  'zap',
  'globe',
  'bot',
  'brain',
  'cpu',
  'server',
  'cloud',
  'rocket',
  'flask',
  'code',
  'bug',
  'wrench',
  'shield',
  'lock',
  'star',
  'sparkles',
  'flame',
  'moon',
  'sun',
  'leaf',
] as const;

export type EnvironmentIcon = (typeof ENVIRONMENT_ICON_OPTIONS)[number];

// Default icons per provider (fallback when icon is null)
export const DEFAULT_PROVIDER_ICONS: Record<EnvironmentProvider, EnvironmentIcon> = {
  anthropic: 'zap',
  openrouter: 'globe',
};

export interface Environment {
  id: string;
  name: string;
  provider: EnvironmentProvider;
  icon: EnvironmentIcon | null; // Custom icon, null uses provider default
  isDefault: boolean;
  variables: Record<string, string>;
  createdAt: number;
  updatedAt: number;
}

// Safe metadata sent to dashboard (no secret values)
export interface EnvironmentMetadata {
  id: string;
  name: string;
  provider: EnvironmentProvider;
  icon: EnvironmentIcon | null; // Custom icon, null uses provider default
  isDefault: boolean;
  variableKeys: string[]; // Only variable names, not values
  createdAt: number;
  updatedAt: number;
}

// Environment API request types
export interface CreateEnvironmentRequest {
  name: string;
  provider: EnvironmentProvider;
  icon?: EnvironmentIcon | null;
  isDefault?: boolean;
  variables: Record<string, string>;
}

export interface UpdateEnvironmentRequest {
  name?: string;
  provider?: EnvironmentProvider;
  icon?: EnvironmentIcon | null;
  isDefault?: boolean;
  variables?: Record<string, string>;
}

// API Request/Response types for REST endpoints

// Clone repository
export interface CloneRequest {
  repoUrl: string;
  projectName?: string;
}

export interface CloneResponse {
  success: boolean;
  projectName?: string;
  path?: string;
  error?: string;
}

// Session archive
export interface ArchiveSessionResponse {
  success: boolean;
  message: string;
  session?: WSSessionInfo;
}

// Hook status notification (from Claude Code plugin)
export interface HookStatusRequest {
  event: string;
  status: SessionStatus;
  attention_reason?: AttentionReason;
  session_id?: string;
  tmux_session?: string;
  project?: string;
  timestamp?: string;
}

// Provider presets for UI
export const ENVIRONMENT_PRESETS: Record<
  EnvironmentProvider,
  {
    label: string;
    defaultVariables: Record<string, string>;
    description: string;
  }
> = {
  anthropic: {
    label: 'Anthropic',
    defaultVariables: {
      ANTHROPIC_API_KEY: '',
    },
    description: 'Direct Anthropic API access',
  },
  openrouter: {
    label: 'OpenRouter',
    defaultVariables: {
      ANTHROPIC_BASE_URL: 'https://openrouter.ai/api',
      ANTHROPIC_AUTH_TOKEN: '',
      ANTHROPIC_API_KEY: '', // Must be explicitly empty
    },
    description: 'Use OpenRouter as Claude provider',
  },
};

// Agent configuration
export interface AgentConfig {
  machine: {
    id: string;
    name: string;
  };
  agent?: {
    port: number;
    url: string; // e.g., "localhost:4678" or "mac.tailnet.ts.net:4678"
  };
  editor?: EditorConfig;
  projects: {
    basePath: string;
    whitelist: string[];
  };
  dashboard: {
    apiUrl: string;
    apiKey: string;
  };
}

// ============================================================================
// Project API Request Types (v7)
// ============================================================================

export interface CreateProjectRequest {
  name: string;
  description?: string;
  trustMode?: boolean;
  baseProject: string; // Must be in projects whitelist
}

export interface UpdateProjectRequest {
  name?: string;
  description?: string;
  status?: ProjectStatus;
  trustMode?: boolean;
}

export interface ProjectResponse {
  success: boolean;
  project?: Project;
  error?: string;
}

export interface ProjectsListResponse {
  success: boolean;
  projects: Project[];
}

// ============================================================================
// Issue API Request Types (v7)
// ============================================================================

export interface CreateIssueRequest {
  projectId?: string; // Optional - if null, creates standalone issue
  title: string;
  description?: string;
  priority?: IssuePriority;
  plan?: string;
}

export interface UpdateIssueRequest {
  title?: string;
  description?: string;
  status?: IssueStatus;
  priority?: IssuePriority;
  plan?: string;
  orderIndex?: number;
}

export interface IssueResponse {
  success: boolean;
  issue?: Issue;
  error?: string;
}

export interface IssuesListResponse {
  success: boolean;
  issues: Issue[];
}

export interface LaunchIssueRequest {
  environmentId?: string; // Optional environment override
}

export interface LaunchIssueResponse {
  success: boolean;
  sessionName?: string;
  error?: string;
}
